### ISSUE TITLE
ReactiveVar doesn't work inside composeWithTracker ?

### ISSUE THREAD

**Issue by crapthings** [arunoda/react-komposer#110]
i just want to make a toggler

```
ActionBar = ({ toggle, content }) => <div>
    <button onClick={() => toggle.set(true)}>new</button>
    {toggle.get() ? content() : ''}
</div>

function tracker(props, onData) {
    const toggle = new ReactiveVar(props.toggle || false)
    const content = function () { return 'actionbar need a content prop' }
    onData(null, { toggle, content })
}

C.ActionBar = container(tracker)(ActionBar)
```

**Comment by crapthings** [comment]
Ahhh forget about it, its my fault

**Comment by crapthings** [comment]
i think i should reopen this.

How to use ReactiveVar inside stateless component ?

**Comment by clayne11** [comment]
Why are you using a `ReactiveVar`? React will automatically re-render the component when props change.

**Comment by macrozone** [comment]
I guess you want to toggle a state of the component.

In this case, a stateful component is a better fit with internal state that you toggle.
OR even better: use https://github.com/acdlite/recompose withState
