### ISSUE TITLE
Need better "Change Default Components" documentation

### ISSUE THREAD

**Issue by kjetilge** [arunoda/react-komposer#114]
I've tried to get this to work following this [gist](https://gist.github.com/PolGuixe/42c572704986b79ea3ce2a8f80ad2409), but to no avail.

**Comment by macrozone** [comment]
just ran into the same issue. 

Problem is that the the default components are set when any component with komposer is required, not when its mounted, which is a design flaw in my opinion:

https://github.com/kadirahq/react-komposer/blob/master/lib/compose.js#L43

These two lines should be somewhere in render()

**Comment by clayne11** [comment]
I agree. This logic needs to be moved inside of render.

**Comment by macrozone** [comment]
sorry for the late answer. I just tested it and it works, so i created a PR: https://github.com/kadirahq/react-komposer/pull/120

You can verify by installing our forked version of the module:

npm install --save git://github.com/panter/react-komposer.git

**Comment by arunoda** [comment]
Thanks. We are going to introduce a new API for 2.x and with that, we won't have this issue.
See: https://github.com/kadirahq/react-komposer/issues/123

**Comment by macrozone** [comment]
Could we still release it on version 1?

Looking forward to the new version, but switching to it comes at a cost, in particular if its a breaking change.

It would be better to having this bugfix on version 1.

**Comment by arunoda** [comment]
@macrozone I just made is almost API compatible with v1.x. But there won't be default loading and error components. We need to load them explicitly. 

It's currently on v2 branch and we are using it production. Will add docs soon.

**Comment by clayne11** [comment]
Why no default loading component? I think it makes a lot of sense to have a default.

**Comment by arunoda** [comment]
We've. You need to provide them manually.
If we've introduce them it's pretty hard to use this with React Native.
There's a way to introduce defaults pretty easily.

**Comment by clayne11** [comment]
But can you still set a default component globally? I guess you could curry the composer function but I think this is something that makes sense to have in the base.

**Comment by arunoda** [comment]
Yes. we could.

**Comment by arunoda** [comment]
I just shipped v2 and we don't ship with default components.
Instead, you need to [do it first](https://github.com/arunoda/react-komposer#set-defaults).
