### ISSUE TITLE
Why the MobX dependency?

### ISSUE THREAD

**Issue by SachaG** [arunoda/react-komposer#115]
Since React Komposer can be used with Meteor, Redux, MobX, etc. why does it depend on MobX specifically?

https://github.com/kadirahq/react-komposer/blob/master/package.json#L55

Isn't it a problem to make every app that uses React Komposer load MobX, even if they don't need it?

**Comment by markoshust** [comment]
Correct, this should be a devDependency

**Comment by arunoda** [comment]
I'm going to handle this in a better way with 2.x https://github.com/kadirahq/react-komposer/issues/123

**Comment by arunoda** [comment]
Just released 2.x and now we don't ship mobx.
