### ISSUE TITLE
add sample how to migrate composeWithTracker to v2

### ISSUE THREAD

**Issue by macrozone** [arunoda/react-komposer#130]
See title,

migration to v2 looks doable, but it's not totally clear. There is also no migration path for meteor-users that still use composeWithTracker.

We should provide such an example or a reference-implementation of a composer that uses tracker underneath

**Comment by arunoda** [comment]
Yep. I will do it today.

**Comment by arunoda** [comment]
Added it here: https://github.com/arunoda/react-komposer#for-meteors-tracker

**Comment by macrozone** [comment]
perfect, thx!

**Comment by TobyEalden** [comment]
still looks a bit confusing to me - use of reactiveMapper for parameter name and actual function, plus shouldn't reactiveMapper mapper return something (or should check for null trackerCleanup before calling it) ?
