### ISSUE TITLE
Can Tracker be an import?

### ISSUE THREAD

**Issue by JeremySaks** [arunoda/react-komposer#44]
I have an issue similar to #27 where `import { composeWithTracker } from 'react-komposer';` gives `Uncaught ReferenceError: Tracker is not defined` unless I first expose `Tracker` as a global.

I'm using 1.3 and bringing in most of my packages through a Meteor wrapper package. If I only do:

``` js
// my local Meteor wrapper package
Package.onUse(function(api) {
  api.use('tracker');
});
```

I get `Tracker is not defined` in my composition file (located in a client/imports folder).

If I `imply` Tracker it works properly:

``` js
Package.onUse(function(api) {
  api.use('tracker');
  api.imply('tracker');
});
```

However what I'd like to do instead is in `client/imports`:

``` js
import React from 'react';
import { Tracker } from 'meteor/tracker';
import { composeWithTracker } from 'react-komposer';
```

But this does not work currently. Alternatively, could react-komposer's `lib/index.js` import `Tracker` so the user app does not need to?

**Comment by clayne11** [comment]
The issue with this is that Tracker is not published to NPM as far as I know, so react-komposer can't import it.

**Comment by arunoda** [comment]
As @clayne11 mentioned, we can't do this for now. I hope we can come back to this after Meteor 1.4.

**Comment by JeremySaks** [comment]
I updated to 2.0 today (works great!) and remembered this old issue I filed. Since `composeWithTracker` is no longer included by default Tracker can be imported instead of exposed globally, and I think this issue can be closed.

**Comment by arunoda** [comment]
Thanks @JeremySaks
