### ISSUE TITLE
Dedicated composer for redux 

### ISSUE THREAD

**Issue by wormyy** [arunoda/react-komposer#79]
Hello, what do you think about having a `composeWithRedux` dedicated method like [react-komposer-redux](https://github.com/sammkj/react-komposer-redux) provides? I think it would DRY up little bit the composers. I would submit a PR if you think it is a good idea.

**Comment by arunoda** [comment]
Yeah. Send a PR.
@sammkj any specific reason about the fork? https://github.com/sammkj/react-komposer-plus

**Comment by sammkj** [comment]
hey @arunoda I'm testing and working on a way to load ddp data into redux store (skip minimongo). Hence, the fork. If you would like, I can submit a PR on this once I'm done.

**Comment by arunoda** [comment]
Okay. If that's purely a composer, I think it's better to publish it as a direct NPM module.
For here, I'd like to get a plain redux composer.

**Comment by arunoda** [comment]
Anyway, @sammkj  I'd like to link your reducer in the README may be in a section called "Additional composers."

**Comment by markoshust** [comment]
Definitely think there is a need for a `composeWithRedux` inside `react-komposer`, if for nothing else than to get rid of the `subscribe()` and initial onData call.

**Comment by markoshust** [comment]
How would one grab `context()` from mantra from within a custom `composeWithRedux` function? I should have a PR back shortly after knowing this as it should be very simple.

**Comment by markoshust** [comment]
Just sent a PR. This is a very basic helper for Redux that avoids the need to call onData twice (and needing `subscribe()`.

I'm using this with Mantra. Here is sample usage:

```
import { useDeps, composeAll } from 'mantra-core';
import composeWithRedux from '/client/modules/core/libs/with_redux';
import Header from '../components/Header';

const onPropsChange = ({ context }, onData) => {
  const { Store } = context();
  const { title } = Store.getState().header;

  onData(null, {
    title,
  });
};

const depsMapper = context => ({
  context: () => context,
});

export default composeAll(
  composeWithRedux(onPropsChange),
  useDeps(depsMapper),
)(Header);
```

By default it will look in context prop for `Store` object. The name can be overridden by passing in a `storeName` options param, and the store itself can be passed in as an option:

Custom name:
```
export default composeAll(
  composeWithRedux(onPropsChange, null, null, {storeName: 'CustomName'),
  useDeps(depsMapper),
)(Header);
```

Passing in store (needed if mantra isn't used):
```
export default composeAll(
  composeWithRedux(onPropsChange, null, null, {store: Store),
  useDeps(depsMapper),
)(Header);
```

**Comment by arunoda** [comment]
@markoshust could you submit a [data loader generator](https://github.com/arunoda/react-komposer#no-utility-composers-for-promises-redux-and-etc) for Redux as suggested here.
(It's for react-komposer v2)

May be for mobx as well.

Idea is to have them outside of the core repo. Anyway, we could link them in the README.
