### ISSUE TITLE
[BUG] Reactive rendering Gone-Wrong !!

### ISSUE THREAD

**Issue by sahanDissanayake** [arunoda/react-komposer#89]
@arunoda Created the repo here to replicate.
https://github.com/canalcasting/IssuFixFrontend/
( Hope I added you properly on github, FYI. Please keep this code secure as this is very sensitive. 👼  )

To be honest I could not replicate so I had to remove most of my code to show you the barebones of the app.

I think this is a bug. Using Meteor version 1.3.2.1 I had an issue with SSR not working with latest meteor versions.

Please let me know anytime if you need any more input from me to get this fixed please.

Thank you.

Tracking it here too https://forums.meteor.com/t/bug-react-komposer-render-crazy-amounts-of-times-when-collection-updated/25518

**Comment by sahanDissanayake** [comment]
@arunoda

**Comment by sahanDissanayake** [comment]
@arunoda  did you get a chance to look at this please ? if not could tell me when you'd be able to look at it. So I can make my plans around the bug :)

**Comment by arunoda** [comment]
I'll do this today. (In daytime).

**Comment by sahanDissanayake** [comment]
Not pushing you or anything Arunoda, But do you have an ETA please ?

Thanks

**Comment by sahanDissanayake** [comment]
@arunoda did you had a chance to look at this repo and the issue that was mentioned ?
Thanks

**Comment by sahanDissanayake** [comment]
@arunoda did you had a chance to look at this repo and the issue that was mentioned ?
Thanks

**Comment by sahanDissanayake** [comment]
Hey Arunoda,
You must be busy in states ⛅  🇺🇸

Do you think you could give me an ETA on this issue please ? a month ? maybe ?

Thanks

**Comment by sahanDissanayake** [comment]
Here we go @arunoda 

I started from kadira-samples/meteor-react... and I re-created the re-render issue here
https://github.com/canalcasting/re-render-bug-simplified/invitations

Please let me know if you'd like to help me and fix this issue

**Comment by sahanDissanayake** [comment]
Hi @arunoda 

I've simplified the issue here
https://github.com/canalcasting/re-render-bug-simplified/invitations

The code should be so easy to understand since it is 80% your's 👍 

Hope to hear from you soon, Lets see why this is happening !!

**Comment by sahanDissanayake** [comment]
Ok I think I found  A solution.

I added ``shouldComponentUpdate()`` to the most top component. So no there are no more re-renders on the children. 

I think this is the way to go. But I will leave this open for a prop advise 👍

**Comment by crapthings** [comment]
hello @sahanDissanayake 

can u post example, how u prevent over rendered ?

**Comment by sahanDissanayake** [comment]
@crapthings I used https://facebook.github.io/react/docs/component-specs.html

So the idea is when u pass props to your children from the parent, I added shouldComponentUpdate to the parent. So the parent will not pass the props down to the children unless the props has been updated. Simple... :)

Read the DOCS carefully.

**Comment by arunoda** [comment]
Check v2. It has fixed this issue.
Check for the [performance](https://github.com/arunoda/react-komposer#performance) section.

BTW: We don't ship Meteor/Tracker support by default.
For that you need to create a [data loader generator](https://github.com/arunoda/react-komposer#no-utility-composers-for-promises-redux-and-etc) as suggested here.
